
github: desirablesolutions
patreon: 
open_collective: 
ko_fi: desirablesolutions
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
