
github: desirablesolutions
patreon: desirablesolutions
open_collective: desirablesolutions
ko_fi: desirablesolutions
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: desirablesolutions
liberapay: desirablesolutions
issuehunt: desirablesolutions
otechie: desirablesolutions
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
